version: '2.1'
networks:
  my-api-network:
    driver: bridge

services:
  wiremock:
    image: wiremock/wiremock:3.5.2-alpine
    container_name: my-api-wiremock
    entrypoint: ["/docker-entrypoint.sh", "--port", "9090"] # "--verbose"
    ports:
      - 9090:9090
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9090" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./wiremock-mappings:/home/wiremock/mappings
    networks:
      - my-api-network

#  rabbitmq:
#    image: rabbitmq:3.6-management-alpine
#    ports:
#      - 15672:15672
#      - 5672:5672
#    container_name: rabbitmq
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_USER=guest
#      - RABBITMQ_PASS=guest
#      - HEALTH_CHECK_CACHE=0
#      - RABBITMQ_DEFAULT_VHOST=b2b
#    healthcheck:
#      test: [ "CMD-SHELL", "nc -z 127.0.0.1 15672" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    networks:
#      - my-api-network

#  api:
#    image: my-api-api:${VERSION}
#    container_name: my-api-api-${VERSION}
#    environment:
#      - SERVER_PORT=8080
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
#      - RABBITMQ_USERNAME=guest
#      - RABBITMQ_PASSWORD=guest
#      - RABBITMQ_VHOST=b2b
#      - RABBITMQ_ADDRESS=amqp://guest:guest@rabbitmq:5672/b2b
#      - MESSAGE_QUEUES={"BR":"BR-my-queue"}
#      - MESSAGE_EXCHANGES_USERS=visit-proof.exchange
#      - MESSAGE_TTL=10
#      - MAX_RETRY=1
#      - FAKE_API_BASE_URL=http://my-api-wiremock:9090
#
#    healthcheck:
#      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    networks:
#      - my-api-network
